### ISSUE TITLE
chmod process hangs

### ISSUE THREAD

**Issue by roman-bronis** [nilfs-dev/nilfs-utils#17]
I wanted to give the NILFS try and play around with it, however I'm not able to change the permissions in freshly made directory.

Steps to reproduce: 
testing NILFS by making NILFS in file and mounting it - **works**.

`dd if=/dev/urandom of=test.fs bs=1M count=500`
`mkfs.nilfs2 -L TestFs test.fs`
`mkdir testfs`
`sudo mount test.fs testfs`
`cd testfs`

Making directory inside - **works**.
`sudo mkdir d1`

Changing directory (and insides) to be rwx for anyone - **hangs the process**.
`sudo chmod -R 777 d1`

Any idea if it is just me or a bug?

EDIT: sorry, nilfs-utils 2.2.8-2, Arch

**Comment by konis** [comment]
I believe this is the same issue as #16.
This was fixed by commit 8301c719a2bd ("nilfs2: fix null pointer dereference at
nilfs_segctor_do_construct()") merged to kernel 5.8-rc1.
The bugfix was back ported to recent stable kernels

  v5.7.3 (linux-5.7.y),  v5.6.19 (linux-5.6.y), v5.4.47 (linux-5.4.y), ...

so, I guess, newer kernels will resolve the issue.
