### ISSUE TITLE
.nilfs file created by mkfs.nilfs2

### ISSUE THREAD

**Issue by sodface** [nilfs-dev/nilfs-utils#21]
This commit eliminated the creation of the .nilfs file:
https://github.com/nilfs-dev/nilfs-utils/commit/2c66e061ceb7a51e3f9bb9d504d516199c833120

The current version and all versions since the above change of sbin/mkfs/mkfs.c in this repo do not contain the code (as expected) but the nilfs-utils-2.2.9.tar.bz2 does and indeed the .nilfs file is being created by mkfs.nilfs2 built from that source archive.

Since the source archive was created recently (long after the change) this seems unexpected?

// edit

My apologies, the code is still present in the 2.2.y branch which explains why it's in the 2.2.9 release. What should distros be packaging? The 2.2.9 release or current master?

**Comment by konis** [comment]
The .nilfs file is an obsolete file and no longer needed. 
That file was initially used for exclusive control of garbage collection (cleaner) in user space, but has been replaced with a different method a long time ago.   The removal of the file in master branch is intentional.

I could have removed it at the 2.2.9 release, but I didn't want to make to much changes other than build issues in 2.2.9, so I put it on hold.  If I publish the next maintenance release (i.e. 2.2.10), I will remove it there to put an end to this matter.   Or if we can release 2.3.0 from the master branch, it will be resolved naturally.

Bascially 2.2.y is the branch for maintenance releases and the master branch is the branch for the next major release.   (That's the reason for the difference whether that file exists or not.)

Although the master branch is stable enough,  distros should preferably package the latest version of the 2.2.y branch, ie 2.2.9 for now because 2.3.0 hasn't been released yet.

I'm sorry that the 2.3.0 release has been stalled because I haven't been able to devote myself to this task for a long time.   Recently, I have resumed NILFS activities, but there are many problems in the kernel module that need to be fixed and I prioritize solving them.  So, I haven't touched the development of the master branch yet.  I believe that once the kernel module has settled down, I will be able to resume this activities as well.

Thank you.

**Comment by sodface** [comment]
Thank you for the response and I understand everything you stated. I maintain the nilfs-utils package for Alpine Linux and will keep it at 2.2.9 per your recommendation. It is welcome news that you are finding time to work on NILFS, thank you for your effort in maintaining this unique and useful filesystem!
